### ISSUE TITLE
AWS extensions zipfile

### ISSUE THREAD

**Issue by krisaoe** [oscarfonts/docker-geoserver#14] opened 2019-06-20 06:58 UTC
The README under /aws states:
"Finally, just create a zip file containing Dockerrun.aws.json, .ebextensions and extensions."

How is this zip file used? Does it need a specific name? I'm not sure how it is pulled in to the build. Can you elaborate please?

Thanks!

**Comment by spawn-guy** [comment] 2021-04-20 08:49
`zip` in this case is an "Application Version" (or a source bundle) in terms of AWS ElasticBeanstalk. https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/applications-sourcebundle.html
this is the stuff that you need to upload to ebTalk when you deploy the app.

alternative approach (as i did) is to use `aws eb-cli` https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3.html 
the downside - eb-cli relies on git to deploy things.
i copied the contents of `aws` folder somewhere outside this repo. created local git repo there, added+committed all the needed files to that git-repo and use `eb deploy`. the command will make a zip file from everything that is committed (yes, it will do `git extract` or something) and will ignore the rest of the files. and will upload and deploy this new version for you

**Comment by victorzinho** [comment] 2023-10-27 08:44
Thanks @spawn-guy for the support!
Closing the ticket since it's quite old and seems resolved. Feel free to reopen if the issue is not resolved.

**Closed by victorzinho** 2023-10-27 08:44 UTC
