### ISSUE TITLE
Enable HTTPS / ssl

### ISSUE THREAD

**Issue by pierrethiriet** [oscarfonts/docker-geoserver#25] opened 2020-05-27 15:42 UTC
Thanks a lot for publishing _docker-geoserver_!
However, I am facing an issue with _ssl/https_. Our web app is now deployed with https and when we do request on Geoserver the browser blocks the request for the lack of Geoserver SSH. 
Is there, by any chance, a simple way to run Geoserver docker under SSH ?
Thanks

**Comment by spawn-guy** [comment] 2021-04-20 08:54
SSL is terminated in front of the Tomcat/docker server. so geoserver sees the requests as non-http.

i am investigating this right now, as i have the same problem on aws+alb.

i'll try to re-configure this inside geoServer first. to see if there is a setting for this. then figure out if TomCat/GS understands `X-Forwarded-Proto` header. and then: or re-configure GeoServer Java-Docker or TomCat in here, or even nginx(that i should disable)

**Comment by spawn-guy** [comment] 2021-04-20 09:32
step one https://docs.geoserver.org/stable/en/user/configuration/globalsettings.html#use-headers-for-proxy-url

**Comment by victorzinho** [comment] 2023-10-26 09:01
Hello @pierrethiriet @spawn-guy 

I'd say https is outside of the scope of this image. As Ian Turton points [here](https://stackoverflow.com/a/60613659), geoserver doesn't care about https and, when needed, should be behind some other component (apache, nginx, ...) that could handle not only ssl but other issues like load balancing, etc. In my previous experience that setup is what worked best.

I understand having geoserver plus that other ssl component in front in a single image could be useful, but in my opinion if the need is there that image should a different one to keep this one simple and decoupled.

**Comment by spawn-guy** [comment] 2023-10-26 09:26
@victorzinho i agree.

In my case ssl is terminated in front of tomcat by aws application load balancer. After terminating ssl alb (and other proxies) add a header x-proto-.. (I mentioned above, I'm on mobile and on vacation - it's difficult to go back and forward here 😅)
The problem is(was???) that geoserver and some plugins generate full urls in certain cases. And these urls not always respect that header and understand that geoserver is behind proxy and under ssl.
My problem is the Web interface redirects to non-ssl URL and creates a cookie for non ssl version of the website. I also have some problems with one of Admin plugins (one of the included ones in this package).
So I am not sure how to fix this with a proxy/load balancer unless it will be parsing and fixing all the contents from geoserver.

PS: last time I checked my install was a half a year ago. And the problem was still there. And my comment here is 3years old 🤣 I can collaborate a bit more thoroughly in a few weeks, if there is interest.

**Comment by victorzinho** [comment] 2023-10-27 09:23
@spawn-guy In the past the proxy base url configuration did the trick for me, everything ogc-related used that configuration and the admin gui worked fine. If there are specific plugins generating full urls that don't use that configuration, or problems with the cookies in the web interface I'm afraid that's out of scope for us. That's probably something for people knowing better the internals of geoserver or those specific plugins; you might find better support in the official geoserver channels in that case.

**Closed** 2023-11-21 08:22 UTC
